# Generated by Django 2.1.7 on 2019-04-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('second_name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=256)),
                ('msg', models.TextField()),
                ('rate', models.CharField(choices=[('1', 'Bad'), ('2', 'Normal'), ('3', 'Good')], max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
